/// 图书分类项（对应 z-library /category/glm_5.2_ark_toC/{slug} 路由）。
///
/// [id] 取自 URL 数字段（如 /category/40/Architecture 中的 40），
/// [slug] 取自 URL 英文段（如 Architecture），[zhName] 为 UI 显示名（翻译后的中文）。
class BookCategory {
  final int id;
  final String slug;
  final String zhName;

  const BookCategory(this.id, this.slug, this.zhName);

  Map<String, dynamic> toJson() => {'id': id, 'slug': slug, 'zhName': zhName};

  factory BookCategory.fromJson(Map<String, dynamic> j) => BookCategory(
    (j['id'] as num).toInt(),
    (j['slug'] ?? '') as String,
    (j['zhName'] ?? '') as String,
  );
}

/// 主分类维度（含若干子分类）。
class BookCategoryGroup {
  final String title;
  final List<BookCategory> children;

  const BookCategoryGroup(this.title, this.children);

  Map<String, dynamic> toJson() => {
    'title': title,
    'children': children.map((c) => c.toJson()).toList(),
  };

  factory BookCategoryGroup.fromJson(Map<String, dynamic> j) =>
      BookCategoryGroup(
        (j['title'] ?? '') as String,
        ((j['children'] as List?) ?? const [])
            .map((e) => BookCategory.fromJson(e as Map<String, dynamic>))
            .toList(),
      );
}

/// 全部分类维度（主分类 -> 子分类两级树）。
///
/// 分类树由 [ZlibraryService.fetchCategories] 抓取 `https://$_domain/categories`
/// 页动态填充，持久化到 SharedPreferences；UI 构建时若已缓存即直接可用。
/// 显示名走 [BookCategories.translate]：英文 -> 中文（末尾计数括号保留），
/// 译名表 [_zhNames] 未收录的返回原文。
class BookCategories {
  BookCategories._();

  /// 是否提供分类筛选能力（[groups] 非空即为 true）。
  static bool get supported => groups.isNotEmpty;

  /// 全部分类维度（按主分类分组）。启动时从缓存加载，fetchCategories 写回。
  static List<BookCategoryGroup> groups = [];

  /// 英文分类名 -> 中文译名表（主分类 + 子分类合并）。
  /// 一次性从 /categories 抓取后翻译写死；新增未收录的分类 [translate] 返回原文。
  /// 跨主分类重名的子分类（如 Others/Reference/Historical）只列首次。
  static const Map<String, String> _zhNames = {
    // -------------------- 主分类 --------------------
    'Arts': '艺术',
    'Astronomy': '天文学',
    'Biography & Autobiography': '传记与自传',
    'Biology and other natural sciences': '生物学与其他自然科学',
    'Business & Economics': '商业与经济',
    'Chemistry': '化学',
    "Children's Books": '儿童读物',
    'Comics & Graphic Novels': '漫画与图像小说',
    'Computers': '计算机',
    'Cookbooks, Food & Wine': '烹饪、美食与酒',
    'Crime, Thrillers & Mystery': '犯罪、惊悚与悬疑',
    'Earth Sciences': '地球科学',
    'Education Studies & Teaching': '教育研究与教学',
    'Engineering': '工程学',
    'Erotica': '情色',
    'Fantasy': '奇幻',
    'Fiction': '小说',
    'History': '历史',
    'Housekeeping & Leisure': '家政与休闲',
    'Jurisprudence & Law': '法理学与法律',
    'Languages': '语言',
    'Linguistics': '语言学',
    'Mathematics': '数学',
    'Medicine': '医学',
    'Nature, Animals & Pets': '自然、动物与宠物',
    'Others': '其他',
    'Physics': '物理学',
    'Poetry': '诗歌',
    'Psychology': '心理学',
    'Reference': '参考',
    'Religion & Spirituality': '宗教与灵性',
    'Romance': '言情',
    'Science (General)': '科学（综合）',
    'Science Fiction': '科幻',
    'Self-Help, Relationships & Lifestyle': '自助、人际关系与生活方式',
    'Society, Politics & Philosophy': '社会、政治与哲学',
    'Sports, Hobbies & Games': '运动、爱好与游戏',
    'Technique': '技术',
    'Travel': '旅行',

    // -------------------- 子分类 --------------------
    // Arts
    'Architecture': '建筑',
    'Business of Art': '艺术商业',
    'Calligraphy': '书法',
    'Conservation, Restoration & Care': '保护、修复与护理',
    'Contemporary Art': '当代艺术',
    'Dance': '舞蹈',
    'Digital Music': '数字音乐',
    'Fashion, Decorative Arts & Design': '时尚、装饰艺术与设计',
    'Film': '电影',
    'Graphic Arts': '平面艺术',
    'History & Criticism': '历史与评论',
    'Museums & Collections': '博物馆与藏品',
    'Music': '音乐',
    'Painting': '绘画',
    'Performing Arts': '表演艺术',
    'Photography': '摄影',
    'Sculpture': '雕塑',
    'Sheet music': '乐谱',
    'Study & Teaching': '学习与教学',
    'Techniques': '技巧',
    // Astronomy
    'Astrobiology': '天体生物学',
    'Astronautics': '航天学',
    'Astronomers & Astrophysicists - Biography': '天文学家与天体物理学家传记',
    'Astronomical Star Guides': '星空观测指南',
    'Astrophysics & Space Science': '天体物理与空间科学',
    'Cosmology': '宇宙学',
    'Galaxies - Astronomical Studies & Observations': '星系——天文研究与观测',
    'History of Astronomy': '天文学史',
    'Outer Space - Observation & Exploration': '外太空——观测与探索',
    'Stars - Astronomical Studies & Observations': '恒星——天文研究与观测',
    'The Solar System - Astronomical Studies & Observations': '太阳系——天文研究与观测',
    'The Universe - Astonomical Studies & Observations': '宇宙——天文研究与观测',
    // Biography & Autobiography
    'Artists, Architects & Photographers': '艺术家、建筑师与摄影师',
    'Business & Finance': '商业与金融',
    'Education Biography': '教育传记',
    'Entertainment Biography': '娱乐传记',
    'Essays, Journals & Letters': '随笔、日记与书信',
    'Film, Television & Music': '电影、电视与音乐',
    'General & Miscellaneous Biography': '综合与其他传记',
    'Historical': '历史',
    'Holocaust': '大屠杀',
    'Literary Biography': '文学传记',
    'Medical, Legal & Social Sciences': '医学、法律与社会科学',
    'Memoir': '回忆录',
    'Novelists, Poets & Playwrights': '小说家、诗人与剧作家',
    'Peoples & Cultures - Biography': '民族与文化传记',
    'Political': '政治',
    'Religious': '宗教',
    'Science, Mathematics & Technology': '科学、数学与技术',
    'Social & Health Issues': '社会与健康议题',
    'Sports & Adventure Biography': '体育与冒险传记',
    'Theatre & Performance Art': '戏剧与表演艺术',
    'Tragic Life Stories': '悲惨人生故事',
    'True Crime': '真实犯罪',
    // Biology and other natural sciences
    'Anatomy': '解剖学',
    'Bioinformatics': '生物信息学',
    'Biology': '生物学',
    'Biophysics': '生物物理',
    'Biostatistics': '生物统计',
    'Biotechnology': '生物技术',
    'Cytology': '细胞学',
    'Ecology': '生态学',
    'Evolution': '进化',
    'Genetics': '遗传学',
    'History of Biology': '生物学史',
    'Human Biology': '人类生物学',
    'Marine: Aquaculture and biology': '海洋：水产养殖与生物学',
    'Microbiology': '微生物学',
    'Molecular': '分子生物学',
    'Mycology': '真菌学',
    'Paleontology': '古生物学',
    'Pathology': '病理学',
    'Plants: Agriculture and Forestry': '植物：农业与林业',
    'Plants: Botany': '植物：植物学',
    'Virology': '病毒学',
    'Zoology': '动物学',
    // Business & Economics
    'Accounting': '会计',
    'E-Commerce': '电子商务',
    'Econometrics': '计量经济学',
    'Economic Theory': '经济理论',
    'Economics': '经济学',
    'History of Economics': '经济学史',
    'Human Resources': '人力资源',
    'Industries': '行业',
    'Investing': '投资',
    'Job Hunting & Careers': '求职与职业',
    'Logistics': '物流',
    'Management & Leadership': '管理与领导力',
    'Markets': '市场',
    'Mathematical Economics': '数理经济学',
    'Personal Finance': '个人理财',
    'Popular': '通俗',
    'Professional Finance': '专业金融',
    'Project Management': '项目管理',
    'Real Estate': '房地产',
    'Responsibility and Business Ethics': '责任与商业伦理',
    'Sales & Marketing': '销售与营销',
    'Small Business': '小企业',
    'Trading': '交易',
    // Chemistry
    'Analytical Chemistry': '分析化学',
    'Biochemistry': '生物化学',
    'Chemistry - General & Miscellaneous': '化学——综合与其他',
    'History of Chemistry': '化学史',
    'Inorganic Chemistry': '无机化学',
    'Microchemistry': '微量化学',
    'Organic Chemistry': '有机化学',
    'Physical Chemistry': '物理化学',
    'Technical & Industrial Chemistry': '技术与工业化学',
    // Children's Books
    'Activities, Crafts & Games': '活动、手工与游戏',
    'Animals': '动物',
    'Arts, Music & Photography': '艺术、音乐与摄影',
    'Cars, Trains & Things That Go': '汽车、火车与交通工具',
    'Computers & Technology': '计算机与技术',
    'Early Learning': '启蒙教育',
    'Education & Reference': '教育与参考',
    'Fairy Tales, Folk Tales & Myths': '童话、民间故事与神话',
    'Geography & Cultures': '地理与文化',
    'Growing Up & Facts of Life': '成长与生活常识',
    'Holidays & Celebrations': '节日与庆典',
    'Humour': '幽默',
    'Literature & Fiction': '文学与小说',
    'Mysteries & Detective Stories': '悬疑与侦探故事',
    'Picture Books': '绘本',
    'Religions': '宗教',
    'Science Fiction & Fantasy': '科幻与奇幻',
    'Science, Nature & How It Works': '科学、自然与原理',
    'Sports & Outdoors': '体育与户外',
    // Comics & Graphic Novels
    'Alternative & Underground Comics': '另类与地下漫画',
    'Anime & Manga': '动漫与漫画',
    'Cartooning': '卡通绘制',
    "Children's": '儿童',
    'Comic Books - History & Criticism': '漫画书——历史与评论',
    'Comics & Graphic Novels - General & Miscellaneous': '漫画与图像小说——综合与其他',
    'DC Comics & Graphic Novels': 'DC 漫画与图像小说',
    'Marvel Comics & Graphic Novels': '漫威漫画与图像小说',
    'Mystery & Thriller Comics & Graphic Novels': '悬疑与惊悚漫画与图像小说',
    'Science Fiction, Fantasy & Horror Comics & Graphic Novels':
        '科幻、奇幻与恐怖漫画与图像小说',
    'Superhero Comics & Graphic Novels': '超级英雄漫画与图像小说',
    // Computers
    'Algorithms and Data Structures': '算法与数据结构',
    'Applications & Software': '应用与软件',
    'Artificial Intelligence (AI)': '人工智能（AI）',
    'Cloud Computing': '云计算',
    'Computer Business & Culture': '计算机商业与文化',
    'Computer Certification & Training': '计算机认证与培训',
    'Computer Graphics & Design': '计算机图形与设计',
    'Computer Science': '计算机科学',
    'Computers - General & Miscellaneous': '计算机——综合与其他',
    'Cryptography': '密码学',
    'Cybernetics': '控制论',
    'Data Science': '数据科学',
    'Databases': '数据库',
    'Digital Photography': '数码摄影',
    'Digital Video': '数码视频',
    'Enterprise Computing Systems': '企业计算系统',
    'Hardware': '硬件',
    'Home Computer User & Beginner': '家庭电脑用户与入门',
    'Human Computer Interaction / Interface (HCI)': '人机交互（HCI）',
    'Information Systems': '信息系统',
    'Internet & World Wide Web': '互联网与万维网',
    'Lectures, monographs': '讲座、专著',
    'Mac OS': 'Mac OS',
    'Media': '媒体',
    'Microsoft Windows': 'Microsoft Windows',
    'Networking': '网络',
    'New to Computing': '计算机入门',
    'Operating Systems': '操作系统',
    'Organization and Data Processing': '组织与数据处理',
    'Other': '其他',
    'PC & Video Games': 'PC 与电子游戏',
    'Professionals': '专业人员',
    'Programming': '编程',
    'Security': '安全',
    'UNIX & Linux': 'UNIX 与 Linux',
    'Web Development': 'Web 开发',
    // Cookbooks, Food & Wine
    'African': '非洲',
    'American': '美式',
    'Asian': '亚洲',
    'Baking & Desserts': '烘焙与甜点',
    'Barbecue & Grilling': '烧烤',
    "Beginner's cookbook": '入门菜谱',
    'French': '法式',
    'Indian & South Asia': '印度与南亚',
    'International': '国际',
    'Italian': '意式',
    'Middle Eastern': '中东',
    'Quick & Easy Meals': '快手菜',
    'Special Diet': '特殊饮食',
    'Vegetarian & Vegan': '素食',
    'Wine & Beverages': '葡萄酒与饮料',
    // Crime, Thrillers & Mystery
    'Action & Adventure': '动作与冒险',
    'Anthologies': '选集',
    'Cozy Mysteries & Amateur Sleuths': '轻松推理与业余侦探',
    'Detective & Crime Fiction': '侦探与犯罪小说',
    'Legal': '法律',
    'Medical': '医疗',
    'Military Thrillers': '军事惊悚',
    'Other Mystery Categories': '其他悬疑分类',
    'Other Thrillers Categories': '其他惊悚分类',
    'Police Stories': '警察故事',
    'Psychological': '心理',
    'Series': '系列',
    'Short Stories': '短篇故事',
    'Spy Stories': '间谍故事',
    'Technothrillers': '科技惊悚',
    'Thrillers': '惊悚',
    'Young Adult': '青少年',
    // Earth Sciences
    'Cartography': '制图学',
    'Earth History': '地球历史',
    'Geochemistry': '地球化学',
    'Geodesy': '大地测量学',
    'Geography': '地理学',
    'Geology': '地质学',
    'Geophysics': '地球物理',
    'Hydrogeology': '水文地质',
    'Meteorology, Climatology': '气象学与气候学',
    'Mineralogy': '矿物学',
    'Mining': '采矿',
    'Oceanography': '海洋学',
    'Palaeontology': '古生物学',
    'Rivers & Lakes': '河流与湖泊',
    'The Environment': '环境',
    'Volcanoes, Earthquakes & Tectonics': '火山、地震与构造',
    // Education Studies & Teaching
    'Academic Administration': '学术管理',
    'Adult & Continuing Education': '成人与继续教育',
    'Bilingual & Multicultural Education': '双语与多元文化教育',
    'Digital Learning': '数字化学习',
    'Education - General & Miscellaneous': '教育——综合与其他',
    'Education Management & Organisation': '教育管理与组织',
    'Educational Guidance & Counseling': '教育指导与咨询',
    'Educational Theory, Research & History': '教育理论、研究与历史',
    'Higher & Further Education': '高等与继续教育',
    'History of Education': '教育史',
    'Homeschooling': '在家上学',
    'Individual Colleges & Universities': '单个学院与大学',
    'International Conferences and Symposiums': '国际会议与研讨会',
    'Learning Experience Design': '学习体验设计',
    'Philosophy of Education': '教育哲学',
    'Pre-school & Early Learning': '学前与早期教育',
    'School Education & Teaching': '学校教育与教学',
    'Special Education': '特殊教育',
    'Studying & Test Preparation': '学习与备考',
    'Teaching & Teacher Training': '教学与教师培训',
    'Teaching - Reading & Language': '教学——阅读与语言',
    'Theses abstracts': '学位论文摘要',
    'Vocational': '职业教育',
    // Engineering
    'Aerospace Engineering': '航空航天工程',
    'Agricultural & Food Sciences': '农业与食品科学',
    'Automotive': '汽车',
    'Bioengineering': '生物工程',
    'Chemical Engineering': '化学工程',
    'Civil & Structural Engineering': '土木与结构工程',
    'Computer Technology': '计算机技术',
    'Construction & Building Trades': '建筑施工与行业',
    'Electrical & Electronic Engineering': '电气与电子工程',
    'Energy & Power Resources': '能源与动力资源',
    'Engineering - General & Miscellaneous': '工程——综合与其他',
    'Engineering Technology': '工程技术',
    'Environmental': '环境',
    'Hydraulic Engineering': '水利工程',
    'Industrial Engineering & Materials Science': '工业工程与材料科学',
    'Mechanical Engineering & Dynamics': '机械工程与动力学',
    'Robotics & Artificial Intelligence': '机器人与人工智能',
    'Social & Cultural Aspects of Technology': '技术的社会与文化层面',
    'Telecommunications': '电信',
    // Erotica
    'Arts & Photography': '艺术与摄影',
    'Comics & Manga': '漫画',
    'Fetishes': '恋物',
    'LGBTQIA+': 'LGBTQIA+',
    'Love, Erotic': '爱情·情色',
    // Fantasy
    'Dark Fantasy': '黑暗奇幻',
    'Fairy Tales': '童话',
    'High Fantasy': '高魔奇幻',
    'Historical Fantasy': '历史奇幻',
    'Low Fantasy': '低魔奇幻',
    'Magical Realism': '魔幻现实主义',
    'Other Fantasy Fiction Categories': '其他奇幻小说分类',
    'Role-Playing Game Fiction': '角色扮演游戏小说',
    'Superhero Fiction': '超级英雄小说',
    'Sword And Sorcery': '剑与魔法',
    'Urban Fantasy': '都市奇幻',
    // Fiction
    'Adventure Stories & Action': '冒险故事与动作',
    'American Fiction': '美国小说',
    'Classics': '经典',
    'Contemporary Fiction': '当代小说',
    'Drama': '戏剧',
    'Essays': '随笔',
    'Family Sagas': '家族史诗',
    'Horror': '恐怖',
    'Literary Fiction': '文学小说',
    'Metaphysical & Visionary': '玄学与幻想',
    'Myths & Folklore': '神话与民俗',
    'Nautical & Maritime Fiction': '航海与海洋小说',
    'Novel': '长篇小说',
    'Peoples & Cultures - Fiction': '民族与文化小说',
    'Religious & Inspirational': '宗教与励志',
    'War & Military Fiction': '战争与军事小说',
    'Westerns': '西部',
    "Women's Fiction": '女性小说',
    'World Fiction': '世界小说',
    // History
    'African History': '非洲历史',
    'American History': '美国历史',
    'American Studies': '美国研究',
    'Ancient History': '古代史',
    'Archaeology': '考古学',
    'Asian History': '亚洲历史',
    'Australian & Oceanian History': '澳大利亚与大洋洲历史',
    'Canadian History': '加拿大历史',
    'Chinese History': '中国历史',
    'Christian History': '基督教历史',
    'European History': '欧洲历史',
    'Historiography': '史学',
    'Indian History': '印度历史',
    'Islamic History': '伊斯兰历史',
    'Latin American History': '拉丁美洲历史',
    'Middle Ages': '中世纪',
    'Middle Eastern History': '中东历史',
    'Military History': '军事历史',
    'Modern History': '近代史',
    'Religious History': '宗教历史',
    'Russian & Soviet History': '俄罗斯与苏联历史',
    'World History': '世界历史',
    // Housekeeping & Leisure
    'Activity & Game Books': '活动与游戏书',
    'Antiques & Collectables': '古董与收藏',
    'Drawing': '绘画',
    'Fashion, Jewelry': '时尚、珠宝',
    'Floral & Nature Crafts': '花艺与自然手工',
    'Games: Board Games': '游戏：桌游',
    'Gardening': '园艺',
    'Glass & Metal Work': '玻璃与金属工艺',
    'Handicraft': '手工',
    'Handicraft: Cutting and Sewing': '手工：裁剪与缝纫',
    'Interior Design & Decoration': '室内设计与装饰',
    'Modelmaking': '模型制作',
    'Papercrafts': '纸艺',
    'Role-Playing & Fantasy Games': '角色扮演与奇幻游戏',
    'Woodworking & Carving': '木工与雕刻',
    // Jurisprudence & Law
    'Administrative Law': '行政法',
    'Business, Commercial & Financial Law': '商业、商事与金融法',
    'Civil Rights Law': '民权法',
    'Constitutional Law': '宪法',
    'Courts & Trial Practice': '法院与审判实务',
    'Criminal Law & Procedure': '刑法与诉讼程序',
    'Criminology, Forensic Science': '犯罪学、法医学',
    'Criminology: Court. Examination': '犯罪学：法庭审查',
    'Environmental Law': '环境法',
    'Family Law': '家庭法',
    'Foreign & International Law': '外国法与国际法',
    'General & Miscellaneous Law': '综合与其他法律',
    'Intellectual Property': '知识产权',
    'Labor Law': '劳动法',
    'Law of Evidence': '证据法',
    'Legal Reference': '法律参考',
    'Legal Theory & Philosophy': '法理学与法哲学',
    'Medical Law': '医疗法',
    'Real Estate & Property Law': '房地产与物权法',
    'Religious Law': '宗教法',
    'Tort & Liability Law': '侵权与责任法',
    // Languages
    'African Languages Reference': '非洲语言参考',
    'Arabic And Hebrew Language Reference': '阿拉伯语与希伯来语参考',
    'Arabic Language Reference': '阿拉伯语参考',
    'Artificial Languages Reference': '人工语言参考',
    'Chinese Language Reference': '中文参考',
    'Comparative Studies': '比较研究',
    'Dictionaries': '词典',
    'English as a Foreign Language & Reference': '英语作为外语与参考',
    'Extinct languages reference': '已消亡语言参考',
    'Finno-Ugric Group Languages Reference': '芬兰-乌戈尔语族参考',
    'French Language Reference': '法语参考',
    'General & Miscellaneous Languages - Reference': '综合与其他语言参考',
    'German Language Reference': '德语参考',
    'Germanic Languages Reference': '日耳曼语族参考',
    'Grammar, dictionaries & phrasebooks': '语法、词典与短语手册',
    'Hindi Language Reference': '印地语参考',
    'Indo-Iranian Languages reference': '印度-伊朗语族参考',
    'Isolated Languages Reference': '孤立语言参考',
    'Italian Language Reference': '意大利语参考',
    'Japanese Language Reference': '日语参考',
    'Korean Language Reference': '韩语参考',
    'Polyglot Dictionaries': '多语词典',
    'Portuguese Language Reference': '葡萄牙语参考',
    'Rhetoric': '修辞学',
    'Romance Languages Reference': '罗曼语族参考',
    'Russian Language Reference': '俄语参考',
    'Slavic Languages Reference': '斯拉夫语族参考',
    'Southeast Asia languages reference': '东南亚语言参考',
    'Spanish Language Reference': '西班牙语参考',
    'Traditional Chinese Language Ref.': '繁体中文参考',
    'Translation Studies': '翻译研究',
    'Turkish Language Reference': '土耳其语参考',
    // Linguistics
    'Applied Linguistics': '应用语言学',
    'Historical & Comparative Linguistics': '历史与比较语言学',
    'Morphology': '词法学',
    'Phonetics and Phonology': '语音学与音系学',
    'Psycholinguistics': '心理语言学',
    'Semiotics': '符号学',
    'Sociolinguistics': '社会语言学',
    'Stylistics': '文体学',
    // Mathematics
    'Algebra': '代数',
    'Analysis': '分析',
    'Applied Mathematics': '应用数学',
    'Automatic Control Theory': '自动控制理论',
    'Combinatorics': '组合数学',
    'Computational Mathematics': '计算数学',
    'Computer Algebra': '计算机代数',
    'Continued fractions': '连分数',
    'Differential Equations': '微分方程',
    'Discrete Mathematics': '离散数学',
    'Dynamical Systems': '动力系统',
    'Functional Analysis': '泛函分析',
    'Fuzzy Logic and Applications': '模糊逻辑与应用',
    'Game Theory': '博弈论',
    'Geometry and Topology': '几何与拓扑',
    'Graph Theory': '图论',
    'History of Mathematics': '数学史',
    'Lectures': '讲义',
    'Logic': '逻辑学',
    'Mathematical Foundations': '数学基础',
    'Mathematical Physics': '数学物理',
    'Mathematical Statistics': '数理统计',
    'Mathematical Theory': '数学理论',
    'Number Theory': '数论',
    'Numerical Analysis': '数值分析',
    'Operator Theory': '算子理论',
    'Optimal control': '最优控制',
    'Optimization. Operations Research': '优化·运筹学',
    'Probability': '概率论',
    'Puzzle': '趣题',
    'Symmetry and group': '对称与群',
    'The complex variable': '复变函数',
    'Wavelets and signal processing': '小波与信号处理',
    // Medicine
    'Anatomy and physiology': '解剖学与生理学',
    'Anesthesiology and Intensive Care': '麻醉学与重症监护',
    'Cardiology': '心脏病学',
    'Chinese Medicine': '中医',
    'Clinical Medicine': '临床医学',
    'Dentistry, Orthodontics': '牙科与正畸',
    'Dermatology': '皮肤科',
    'Diabetes': '糖尿病',
    'Diseases': '疾病',
    'Emergency Medicine': '急诊医学',
    'Endocrinology': '内分泌学',
    'ENT': '耳鼻喉科',
    'Epidemiology': '流行病学',
    'Feng Shui': '风水',
    'First Aid': '急救',
    'Forensic Medicine': '法医学',
    'Health-Related Professions': '健康相关职业',
    'Histology': '组织学',
    'History of Medicine': '医学史',
    'Homeopathy': '顺势疗法',
    'Immunology': '免疫学',
    'Infectious diseases': '传染病',
    'Internal Medicine': '内科',
    'Medicine & Nursing Reference': '医学与护理参考',
    'Medicine & Nursing Test Prep': '医学与护理考试',
    'Molecular Medicine': '分子医学',
    'Natural Medicine': '自然医学',
    'Nephrology': '肾脏病学',
    'Neurology': '神经病学',
    'Neuroscience': '神经科学',
    'Nursing': '护理',
    'Obstetrics & Gynecology': '妇产科',
    'Oncology': '肿瘤学',
    'Ophthalmology': '眼科',
    'Pediatrics': '儿科',
    'Pharmacology': '药理学',
    'Popular scientific literature': '科普读物',
    'Psychiatry': '精神病学',
    'Public Health & Medical Informatics': '公共卫生与医学信息学',
    'Radiology': '放射科',
    'Rehabilitation': '康复',
    'Surgery, Orthopedics': '外科与骨科',
    'Therapy, Psychotherapy': '心理治疗',
    'Trial': '临床试验',
    'Urology': '泌尿科',
    'Veterinary Medicine': '兽医学',
    'Yoga, Ayurveda': '瑜伽与阿育吠陀',
    // Nature, Animals & Pets
    'Animal Care & Pets': '动物护理与宠物',
    'Birds': '鸟类',
    'Cats': '猫',
    'Dinosaurs': '恐龙',
    'Dogs': '狗',
    'Exotic & Other Pets': '异宠与其他宠物',
    'Field Guides': '野外指南',
    'Fossils': '化石',
    'Home Aquarium': '家庭水族',
    'Horses': '马',
    'Insects & Arachnids': '昆虫与蛛形纲',
    'Mammals': '哺乳动物',
    'Marine & Aquatic Life': '海洋与水生生物',
    'Natural Disasters': '自然灾害',
    'Natural History': '自然史',
    'Natural Terrain': '自然地形',
    'Nature - Other': '自然——其他',
    'Pet Birds': '宠物鸟',
    'Pet Fish': '观赏鱼',
    'Pet Memoirs': '宠物回忆录',
    'Pet Mice, Rabbits, Hamsters, Etc.': '宠物鼠、兔、仓鼠等',
    'Pet Pigs': '宠物猪',
    'Pet Reptiles & Amphibians': '宠物爬行与两栖动物',
    'Pets - General & Miscellaneous': '宠物——综合与其他',
    'Plants & Fungi': '植物与真菌',
    "Stargazing - Amateur's Manuals": '观星——业余手册',
    'Weather': '天气',
    // Others
    'Comedy': '喜剧',
    // Physics
    'Atomic & Molecular': '原子与分子',
    'Chaos & Dynamic Systems': '混沌与动力系统',
    'Crystal Physics': '晶体物理',
    'Electricity and Magnetism': '电磁学',
    'Electrodynamics': '电动力学',
    'General Courses': '普通课程',
    'History of Physics': '物理学史',
    'Light, Optics & Laser': '光、光学与激光',
    'Mechanics': '力学',
    'Mechanics: Fluid Mechanics': '力学：流体力学',
    'Mechanics: Mechanics of deformable bodies': '力学：变形体力学',
    'Mechanics: Nonlinear dynamics and chaos': '力学：非线性动力学与混沌',
    'Mechanics: Oscillations and Waves': '力学：振动与波',
    'Mechanics: Strength of Materials': '力学：材料力学',
    'Mechanics: Theory of Elasticity': '力学：弹性理论',
    'Nuclear': '核物理',
    'Optics': '光学',
    'Physics of the Atmosphere': '大气物理',
    'Plasma Physics': '等离子体物理',
    'Quantum Mechanics': '量子力学',
    'Quantum Physics': '量子物理',
    'Relativity': '相对论',
    'Solid State Physics': '固体物理',
    'Spectroscopy': '光谱学',
    'States of Matter': '物态',
    'Theoretical Physics': '理论物理',
    'Theory of Relativity and Gravitation': '相对论与引力理论',
    'Thermodynamics': '热力学',
    // Poetry
    'African poetry': '非洲诗歌',
    'American Poetry': '美国诗歌',
    'Ancient & Classical Poetry': '古代与古典诗歌',
    'Arabic & Middle Eastern Poetry': '阿拉伯与中东诗歌',
    'Asian Poetry': '亚洲诗歌',
    'Australian, New Zealand, & Pacific Island Poetry': '澳大利亚、新西兰与太平洋岛国诗歌',
    'Canadian Poetry': '加拿大诗歌',
    'English, Irish, & Scottish Poetry': '英格兰、爱尔兰与苏格兰诗歌',
    'European Poetry': '欧洲诗歌',
    'General & Miscellaneous Poetry': '综合与其他诗歌',
    'Indian poetry': '印度诗歌',
    'Inspirational & Religious Poetry': '励志与宗教诗歌',
    'Latin American & Caribbean Poetry': '拉丁美洲与加勒比诗歌',
    'Poetics': '诗学',
    'Poetry Anthologies': '诗歌选集',
    'Russian Poetry': '俄罗斯诗歌',
    // Psychology
    'Clinical Psychology': '临床心理学',
    'Cognitive Psychology': '认知心理学',
    'Developmental Psychology': '发展心理学',
    'Neuropsychology': '神经心理学',
    'Pedagogy': '教育学',
    'Psychoanalysis': '精神分析',
    'Psychological Disorders': '心理障碍',
    'Psychology - Theory, History & Research': '心理学——理论、历史与研究',
    'Psychology of Crime and Justice': '犯罪与司法心理学',
    'Psychopathy': '精神病态',
    'Psychotherapy': '心理治疗',
    'Social Psychology': '社会心理学',
    // Reference
    'Almanacs & Yearbooks': '年鉴与年刊',
    'Atlases & Maps': '地图集与地图',
    'Consumer Guides': '消费指南',
    'Encyclopaedias': '百科全书',
    'Genealogy & Family History': '家谱与家族史',
    'Library & Information Science': '图书馆与信息科学',
    'Other Reference By Subject': '其他主题参考',
    'School Guides & Test Preparation': '学校指南与备考',
    'Thesauri': '分类词典',
    'Writing': '写作',
    // Religion & Spirituality
    'Astrology': '占星术',
    'Atheism & Agnosticism': '无神论与不可知论',
    'Bible': '圣经',
    'Buddhism': '佛教',
    'Christianity': '基督教',
    'Esoteric, Occult, & Divination': '神秘学、秘术与占卜',
    'Hinduism': '印度教',
    'Islam': '伊斯兰教',
    'Jainism': '耆那教',
    'Judaism': '犹太教',
    'Kabbalah': '卡巴拉',
    'Other Religions': '其他宗教',
    'Religious Conflict': '宗教冲突',
    'Religious Studies': '宗教研究',
    'Sacred Texts': '圣典',
    'Sikhism': '锡克教',
    'Spirituality': '灵性',
    'Taoism & Confucianism': '道教与儒教',
    'Theology': '神学',
    'Theosophy & New Age': '神智学与新纪元',
    'Wicca': '威卡',
    // Romance
    'Christmas Romance': '圣诞言情',
    'Collections & Anthologies': '选集与合集',
    'Contemporary Romance': '当代言情',
    'Dark Romance': '黑暗言情',
    'Erotic Romance': '情色言情',
    'Gothic Romance': '哥特言情',
    'Historical Romance': '历史言情',
    'Interracial': '跨种族',
    'LGBTQ+ Romance': 'LGBTQ+ 言情',
    'Military Romance': '军旅言情',
    'New Adult': '新成人',
    'Other Romance Categories': '其他言情分类',
    'Paranormal Romance': '灵异言情',
    'Religious Romance': '宗教言情',
    'Romantic Comedy': '浪漫喜剧',
    'Romantic Westerns': '浪漫西部',
    'Science Fiction Romance': '科幻言情',
    'Sport Romance': '体育言情',
    'Time Travel Romance': '时间旅行言情',
    'Young Adult Romance': '青少年言情',
    // Science (General)
    'History of Science': '科学史',
    'Research & Development': '研发',
    'Science of Science': '科学的科学',
    'Scientific and popular: Journalism': '科普与通俗：新闻',
    'Scientific-popular': '科普',
    'Theories of Science': '科学理论',
    // Science Fiction
    'Alternate Realities': '平行现实',
    'Anthologies & Short Stories': '选集与短篇',
    'Apocalyptic': '末日',
    'Cyberpunk': '赛博朋克',
    'Dystopian Fiction': '反乌托邦小说',
    'Fantasy Fiction': '奇幻小说',
    'High Tech & Hard Sci-Fi': '高科技与硬科幻',
    'Military Science Fiction': '军事科幻',
    'Other Sci-Fi': '其他科幻',
    'Space Opera': '太空歌剧',
    'Space Western': '太空西部',
    'Steampunk': '蒸汽朋克',
    'Supernatural Fiction': '超自然小说',
    'Time Travel': '时间旅行',
    'Urban Fiction': '都市小说',
    'Utopian Fiction': '乌托邦小说',
    // Self-Help, Relationships & Lifestyle
    'Addiction & Recovery': '成瘾与康复',
    'Aging': '衰老',
    'Alternative Medicine & Natural Healing': '替代医学与自然疗法',
    'Beauty & Fashion': '美容与时尚',
    'Dating': '约会',
    'Diet & Nutrition': '饮食与营养',
    'Digital Lifestyle': '数字生活方式',
    'Divorce': '离婚',
    'Emotional Healing': '情感疗愈',
    'Exercise & Fitness': '锻炼与健身',
    'Families & Parents': '家庭与父母',
    'Health - Diseases & Disorders': '健康——疾病与失调',
    'Love & Romance': '爱情与浪漫',
    'Marriage': '婚姻',
    "Men's Health & Lifestyle": '男性健康与生活方式',
    'Personal Growth & Inspiration': '个人成长与励志',
    'Pregnancy & Childcare': '怀孕与育儿',
    'Psychological Self-Help': '心理自助',
    'Relationships': '人际关系',
    'Sexuality': '性',
    'The Art of Communication': '沟通的艺术',
    'Weddings': '婚礼',
    "Women's Health & Lifestyle": '女性健康与生活方式',
    // Society, Politics & Philosophy
    'Ancient & Medieval Philosophy': '古代与中世纪哲学',
    'Anthropology': '人类学',
    'Asian Philosophy': '亚洲哲学',
    'Cultural': '文化',
    'Ethics': '伦理学',
    'Ethnography': '民族志',
    'European & American Philosophy': '欧洲与美国哲学',
    'General & Miscellaneous Philosophy': '综合与其他哲学',
    'Geopolitics': '地缘政治',
    'Government & Politics': '政府与政治',
    'International Relations': '国际关系',
    'Journalism, Media': '新闻、媒体',
    'Major Branches of Philosophical Study': '哲学研究主要分支',
    'Philosophical Positions & Movements': '哲学立场与流派',
    'Philosophy of Science': '科学哲学',
    'Politics': '政治',
    'Renaissance & Modern Philosophy': '文艺复兴与现代哲学',
    'Social Sciences': '社会科学',
    'Sociology': '社会学',
    'Warfare & Defence': '战争与国防',
    "Women's Studies": '女性研究',
    // Sports, Hobbies & Games
    'Air Sports': '航空运动',
    'Athletics & Gymnastics': '田径与体操',
    'Ball Games': '球类运动',
    'Bike': '自行车',
    'Boating & Sailing': '划船与帆船',
    'Bodybuilding': '健美',
    'Chess': '国际象棋',
    'Climbing & Mountaineering': '攀岩与登山',
    'Fencing': '击剑',
    'Football & Rugby': '足球与橄榄球',
    'Games With Bat and Ball': '击球运动',
    'Golf': '高尔夫',
    'Hockey': '曲棍球',
    'Hunting & Fishing': '狩猎与钓鱼',
    'Martial Arts': '武术',
    'Motor Sports': '赛车运动',
    'Olympics & Olympic Sports': '奥运会与奥林匹克运动',
    'Other Sports': '其他运动',
    'Outdoor & Adventure Sports': '户外与冒险运动',
    'Survival': '野外生存',
    'Training & Coaching': '训练与指导',
    'Water Sports': '水上运动',
    'Winter Sports': '冬季运动',
    // Technique
    'Aerospace Equipment': '航空航天设备',
    'Automation': '自动化',
    'Communication': '通信',
    'Construction': '建筑',
    'Construction: Cement Industry': '建筑：水泥工业',
    'Construction: Renovation and interior design': '建筑：翻新与室内设计',
    'Construction: Ventilation and Air Conditioning': '建筑：通风与空调',
    'Electronics': '电子学',
    'Electronics: Fiber Optics': '电子：光纤',
    'Electronics: Hardware': '电子：硬件',
    'Electronics: Home Electronics': '电子：家用电子',
    'Electronics: Microprocessor Technology': '电子：微处理器技术',
    'Electronics: Radio': '电子：无线电',
    'Electronics: Robotics': '电子：机器人',
    'Electronics: Signal Processing': '电子：信号处理',
    'Electronics: Telecommunications': '电子：电信',
    'Electronics: TV. Video': '电子：电视与视频',
    'Electronics: VLSI': '电子：超大规模集成电路',
    'Energy': '能源',
    'Energy: Renewable Energy': '能源：可再生能源',
    'Experiments, Instruments & Measurements': '实验、仪器与测量',
    'Food Manufacturing': '食品制造',
    'Fuel Technology': '燃料技术',
    'Heat': '热学',
    'Industrial Equipment and Technology': '工业设备与技术',
    'Light Industry': '轻工业',
    'Marine & Nautical': '海事与航海',
    'Materials': '材料',
    'Metallurgy': '冶金',
    'Metrology': '计量学',
    'Military equipment': '军事装备',
    'Military equipment: Missiles': '军事装备：导弹',
    'Military equipment: Weapon': '军事装备：武器',
    'Nanotechnology': '纳米技术',
    'Oil and Gas Technologies': '石油与天然气技术',
    'Patent Business. Ingenuity. Innovation': '专利业务·独创·创新',
    'Publishing': '出版',
    'Refrigeration': '制冷',
    'Regulatory Literature': '规范文献',
    'Safety and Security': '安全与安保',
    'Transport': '运输',
    'Transportation: Aviation': '交通：航空',
    'Transportation: Cars, Motorcycles': '交通：汽车与摩托',
    'Transportation: Rail': '交通：铁路',
    'Transportation: Ships': '交通：船舶',
    'Water Treatment': '水处理',
    // Travel
    'Africa - Travel': '非洲旅行',
    'Asia - Travel': '亚洲旅行',
    'Australia & Oceania - Travel': '澳大利亚与大洋洲旅行',
    'Canadian & North American Travel': '加拿大与北美旅行',
    'Europe - Travel': '欧洲旅行',
    'Food, Lodging & Transportation': '餐饮、住宿与交通',
    'Latin American & Caribbean Travel': '拉丁美洲与加勒比旅行',
    'Middle East - Travel': '中东旅行',
    'Pictorial': '图册',
    'Specialty Travel': '主题旅行',
    'Travel - Cities of the World': '旅行——世界城市',
    'Travel - General & Miscellaneous': '旅行——综合与其他',
    'Travel - Interests, Activities & Accommodations': '旅行——兴趣、活动与住宿',
    'Travel - Natural & Man-made Wonders of the World': '旅行——世界自然与人造奇观',
    'Travel Essays & Descriptions': '游记与描述',
    'Travel Photography': '旅行摄影',
    'Travel Writing': '旅行写作',
    'United States of America - Travel': '美国旅行',
  };

  /// 上下文相关的译名覆盖：key = `'$mainName|$baseName'`。
  /// 仅用于同名子分类在不同主分类下需不同译名的场景（如 Elementary：教育=小学、数学=初等数学）。
  static const Map<String, String> _zhNamesOverride = {
    'Education Studies & Teaching|Elementary': '小学',
    'Mathematics|Elementary': '初等数学',
  };

  /// 将抓到的英文分类名翻译为中文显示名。
  ///
  /// [context] 为主分类英文名（子分类翻译时传入，用于 [_zhNamesOverride] 消歧）。
  /// 末尾的 `(数字)` 计数保留（如 `Architecture (22751)` -> `建筑 (22751)`）；
  /// 译名表未收录的返回原文。
  static String translate(String raw, {String? context}) {
    if (raw.isEmpty) return raw;
    final m = RegExp(r'\s*\((\d[\d,]*)\)\s*$').firstMatch(raw);
    if (m != null) {
      final base = raw.substring(0, m.start).trim();
      final suffix = raw.substring(m.start);
      final zh = _lookup(base, context);
      return zh == null ? raw : '$zh$suffix';
    }
    return _lookup(raw, context) ?? raw;
  }

  static String? _lookup(String base, String? context) {
    if (context != null) {
      final ov = _zhNamesOverride['$context|$base'];
      if (ov != null) return ov;
    }
    return _zhNames[base];
  }
}

/// 分类浏览的额外过滤条件可选项。
///
/// 年份为范围输入（无固定选项）；语言/格式为多选，值即发往服务端的实际参数。
class BookCategoryFilters {
  BookCategoryFilters._();

  /// 语言选项：label 为中文显示，value 为发往服务端的实际参数值（原样拼入 URL）。
  /// 注意 `traditional+chinese` 的 `+` 不做编码，URL 里就是这个字面量。
  static const List<({String value, String label})> languages = [
    (value: 'chinese', label: '中文'),
    (value: 'traditional+chinese', label: '繁体中文'),
    (value: 'english', label: '英语'),
    (value: 'mongolian', label: '蒙古语'),
    (value: 'tibetan', label: '藏语'),
    (value: 'uighur', label: '维吾尔语'),
    (value: 'french', label: '法语'),
    (value: 'japanese', label: '日语'),
    (value: 'arabic', label: '阿拉伯语'),
    (value: 'german', label: '德语'),
    (value: 'italian', label: '意大利语'),
    (value: 'portuguese', label: '葡萄牙语'),
    (value: 'russian', label: '俄语'),
    (value: 'spanish', label: '西班牙语'),
    (value: 'thai', label: '泰语'),
    (value: 'latin', label: '拉丁语'),
  ];

  /// 格式选项（值即显示，无需翻译）。
  static const List<String> extensions = [
    'EPUB',
    'MOBI',
    'AZW3',
    'AZW',
    'PDF',
    'TXT',
  ];
}
